version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    machine: true
    working_directory: ~/project
    steps:
      - checkout:
          path: ~/project
      - run: docker-compose -f docker-compose.test.yaml -p ci build
      - run: docker-compose -f docker-compose.test.yaml -p ci up --exit-code-from sut

workflows:
  main:
    jobs:
      - build-and-test
